# kdm bash-env
# .kdm/bashrc

# shellcheck disable=SC1090
# shellcheck disable=SC1091

# Array of possible global bashrc files
ARRAY_SOURCE_GLOBAL=(
/etc/bash.bashrc
/etc/bashrc
)

# Array of function files to source from ~/.kdm/bashrc.d
ARRAY_SOURCE_FUNCTIONS_BACKUP=(
android
array
find
fix
md5
show
color
misc
text
ping
time
conversion
ssh
git
net
prompt
motd
kdm
update
macos
linux
auto-sudo
alias-generation
)

# Build array of function files to source from ~/.kdm/bashrc.d
ARRAY_SOURCE_FUNCTIONS=($(ls -Fh1 "${BASH_ENV_DIR_BASHRC}/functions-"* 2> /dev/null))

# Build array of alias files to source from ~/.kdm/bashrc.d
ARRAY_SOURCE_ALIASES=($(ls -Fh1 "${BASH_ENV_DIR_BASHRC}/aliases-"* 2> /dev/null))


# Source possible global bashrc(s)
for FILE in "${ARRAY_SOURCE_GLOBAL[@]}"; do
	[[ -f "${GLOBAL}" ]] && . "${FILE}"
done; unset FILE

# Source function files
for FILE in "${ARRAY_SOURCE_FUNCTIONS[@]}"; do
	. "${FILE}"
done; unset FILE

# Source alias files
for FILE in "${ARRAY_SOURCE_ALIASES[@]}"; do
	. "${FILE}"
done; unset FILE

# vim: set syntax=sh filetype=sh ts=2 sw=2 tw=0 noet :
