#!/usr/bin/env bash

# shellcheck disable=SC1090

TIMEFORMAT_OLD="${TIMEFORMAT}"

export TIMEFORMAT_RACE="true"

DIR_TEMP="$(mktemp -d)"
FILE_TEMP_RAW="${DIR_TEMP}/race-times-raw.csv"
FILE_TEMP_SORTED="${DIR_TEMP}/race-times-sorted.csv"


mapfile -t ARRAY_FILES < <(find "${HOME}/.kdm/rc.d" -maxdepth 1 -type f -executable | sort)

for FILE_NAME in "${ARRAY_FILES[@]}"; do
	TIME_START="$(date '+%s%N')"
	. "${FILE_NAME}"
	TIME_END="$(date '+%s%N')"

	MILLISECONDS="$(bc -l <<< "scale=3; (${TIME_END}-${TIME_START})/1000000")"

	echo "${MILLISECONDS},${FILE_NAME}" >> "${FILE_TEMP_RAW}"
done

export TIMEFORMAT="${TIMEFORMAT_OLD}"

unset TIMEFORMAT_RACE


echo "Milliseconds elapsed, file name" >> "${FILE_TEMP_SORTED}"
sort -nr "${FILE_TEMP_RAW}" >> "${FILE_TEMP_SORTED}"

cat "${FILE_TEMP_SORTED}"

rm -rf "${DIR_TEMP}"


# vim: set filetype=sh ts=2 sw=2 tw=0 noet :
