#!/usr/bin/env bash

BRANCH="$(git symbolic-ref --short HEAD 2> /dev/null)"

if [[ -z "${BRANCH}" ]]; then
	BRANCH="$(git branch --show-current)"
fi

if [[ -z "${BRANCH}" ]]; then
	echo 'Error : No branch detected'
	exit 1
fi

export BRANCH
