#!/usr/bin/env bash

ARRAY_DEPS=(jq npm yarn)

for DEP in "${ARRAY_DEPS[@]}"; do
	if ! hash "${DEP}" > /dev/null 2>&1; then
		echo "Command unavailable : '${DEP}', cannot continue"
		exit 1
	fi
done


cd "${HOME}/.config/coc/extensions" || exit 2
echo "Executing 'npm install' in ~/.config/coc/extensions"
npm install --install-strategy=shallow --ignore-scripts --no-bin-links --no-package-lock --omit=dev
echo; echo

#cd "${HOME}/.config/coc/extensions/node_modules/coc-json" || exit 3
#echo "Executing 'yarn install' in ~/.config/coc/extensions/node_modules/coc-json"
#rm -f ./package-lock.json > /dev/null 2>&1
#yarn install --ignore-scripts --ignore-engines --network-concurrency "$(nproc)" --non-interactive
#echo; echo
#
#cd "${HOME}/.config/coc/extensions/node_modules/coc-yaml" || exit 4
#echo "Executing 'yarn install' in ~/.config/coc/extensions/node_modules/coc-yaml"
#rm -f ./package-lock.json > /dev/null 2>&1
#yarn install --ignore-scripts --ignore-engines --network-concurrency "$(nproc)" --non-interactive
#echo; echo

cd "${HOME}/.vim/pack/kdm/coc.nvim" || exit 5
echo "Executing 'npm ci' in ~/.vim/pack/kdm/coc.nvim"
#rm -f ./package-lock.json > /dev/null 2>&1
npm ci
#yarn install --frozen-lockfile --network-concurrency "$(nproc)" --non-interactive
echo; echo

#echo "Fixing coc-svg svgo dependency symlink"
#ln -fs "${HOME}/.config/coc/extensions/node_modules/svgo" "${HOME}/.config/coc/extensions/node_modules/coc-svg/node_modules/svgo"
#echo;echo
