#!/usr/bin/env bash

PKG_MANAGER="yarn"


ARRAY_DEPS=(jq ncu "${PKG_MANAGER}")

for DEP in "${ARRAY_DEPS[@]}"; do
	if ! hash "${DEP}" > /dev/null 2>&1; then
		echo "Command unavailable : '${DEP}', cannot continue"
		exit 2
	fi
done


cd "${HOME}/.config/coc/extensions" || exit 1
echo "Checking for updates"
if ncu --errorLevel 2 --loglevel silent --packageManager "${PKG_MANAGER}" --upgrade; then
	echo "No update needed"
fi

echo "Formatting/sorting package.json"
FILE_TEMP="$(mktemp)"
jq -S --tab . ./package.json > "${FILE_TEMP}"
mv --force --verbose "${FILE_TEMP}" ./package.json


~/.config/coc/extensions/install
