#!/usr/bin/env bash

UPDATE_REQUIRED="true"
PKG_MANAGER="npm"


ARRAY_DEPS=(jq ncu "${PKG_MANAGER}")

for DEP in "${ARRAY_DEPS[@]}"; do
	if ! hash "${DEP}" > /dev/null 2>&1; then
		echo "Command unavailable : '${DEP}', cannot continue"
		exit 2
	fi
done


cd "${HOME}/.config/coc/extensions" || exit 1

echo "Checking for updates"
# For some reason, `--upgrade` instead of `-u` makes ncu say "No dependencies" and nothing works
if ncu --errorLevel 2 --loglevel silent --packageManager "${PKG_MANAGER}" -u; then
	echo "No update required"
	UPDATE_REQUIRED="false"
fi

echo "Formatting/sorting package.json"
FILE_TEMP="$(mktemp)"
jq -S --tab . ./package.json > "${FILE_TEMP}"
mv --force "${FILE_TEMP}" ./package.json

[[ "${UPDATE_REQUIRED}" == "false" ]] && exit 0

~/.config/coc/extensions/install
