#!/usr/bin/env bash


mkdir -p "${HOME}/.config/coc/extensions"

cd "${HOME}/.config/coc/extensions" || exit 1


if ! hash ncu > /dev/null 2>&1; then
	echo "Command unavailable : 'ncu', cannot continue"
	exit 2
fi

if ! hash yarn > /dev/null 2>&1; then
	echo "Command unavailable : 'yarn', cannot continue"
	exit 3
fi

if ! hash jq > /dev/null 2>&1; then
	echo "Command unavailable : 'jq', cannot continue"
	exit 4
fi


echo "Checking for updates"
if ncu --errorLevel 2 --loglevel silent --packageManager yarn --upgrade; then
	echo "No update needed"
	exit 0
fi

echo "Cleaning up old modules"
rm -rf ./node_modules/ ./package-lock.json

echo "Formatting/sorting package.json"
FILE_TEMP="$(mktemp)"
jq -S --tab . ./package.json > "${FILE_TEMP}"
mv --force --verbose "${FILE_TEMP}" ./package.json

echo "Executing 'yarn'"
yarn
echo; echo

echo "Performing nvim CocUpdateSync"
nvim -c 'CocUpdateSync|q'
