#!/usr/bin/env bash

TIMEFORMAT_OLD="${TIMEFORMAT}"

export TIMEFORMAT_RACE="true"

echo "File name,Time elapsed"

mapfile -t ARRAY_FILES < <(find "${HOME}/.kdm/profile.d" -maxdepth 1 -type f -executable | sort)

for FILE_NAME in "${ARRAY_FILES[@]}"; do
	echo -n "${FILE_NAME//$HOME\/\.kdm\/profile\.d\//},"

	TIME_START="$(date '+%s%N')"
	. "${FILE_NAME}"
	TIME_END="$(date '+%s%N')"
	echo "${TIME_START},${TIME_END},$((TIME_END-TIME_START)) ns"
done

export TIMEFORMAT="${TIMEFORMAT_OLD}"

unset TIMEFORMAT_RACE


# vim: set filetype=sh ts=2 sw=2 tw=0 noet :
