#!/usr/bin/env bash

TIMEFORMAT_OLD="${TIMEFORMAT}"

export TIMEFORMAT_RACE="true"

echo "File name,Time elapsed"

for FILE_NAME in ./*-*; do
	echo -n "${FILE_NAME//\.\//},"

	export TIMEFORMAT='%3R'
	time source "${FILE_NAME}"
done

export TIMEFORMAT="${TIMEFORMAT_OLD}"

unset TIMEFORMAT_RACE
